import { useState, useEffect, useCallback, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Bot, User, Sparkles, Volume2, VolumeX } from "lucide-react";

const useMessageSound = () => {
  const audioCtxRef = useRef<AudioContext | null>(null);

  const getCtx = useCallback(() => {
    if (!audioCtxRef.current) {
      audioCtxRef.current = new AudioContext();
    }
    return audioCtxRef.current;
  }, []);

  const playPop = useCallback((isAssistant: boolean) => {
    try {
      const ctx = getCtx();
      const osc = ctx.createOscillator();
      const gain = ctx.createGain();
      osc.connect(gain);
      gain.connect(ctx.destination);
      osc.type = "sine";
      osc.frequency.setValueAtTime(isAssistant ? 880 : 660, ctx.currentTime);
      osc.frequency.exponentialRampToValueAtTime(isAssistant ? 1200 : 440, ctx.currentTime + 0.08);
      gain.gain.setValueAtTime(0.12, ctx.currentTime);
      gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.15);
      osc.start(ctx.currentTime);
      osc.stop(ctx.currentTime + 0.15);
    } catch {}
  }, [getCtx]);

  return playPop;
};

const demoConversation = [
  { role: "user", text: "What are the four forces of flight?" },
  {
    role: "assistant",
    text: "Great question! Instead of just listing them, let's think about it. When you're sitting in a parked aircraft, what force is pulling the airplane toward the ground?",
  },
  { role: "user", text: "That would be gravity — so weight?" },
  {
    role: "assistant",
    text: "Exactly! Weight acts downward through the center of gravity. Now, what force opposes weight to keep you airborne? Hint: it's generated by the wings. (Ref: PHAK Ch. 5)",
  },
  { role: "user", text: "Lift!" },
  {
    role: "assistant",
    text: "✅ Correct! Lift opposes weight and is produced by differential pressure on the wing surfaces per Bernoulli's principle. Two down, two to go — what force propels the airplane forward?",
  },
];

const AnimatedChatDemo = () => {
  const [visibleCount, setVisibleCount] = useState(0);
  const [typing, setTyping] = useState(false);

  useEffect(() => {
    if (visibleCount >= demoConversation.length) {
      // Reset after a pause
      const resetTimer = setTimeout(() => {
        setVisibleCount(0);
      }, 4000);
      return () => clearTimeout(resetTimer);
    }

    const nextMsg = demoConversation[visibleCount];
    const delay = nextMsg.role === "assistant" ? 1800 : 1000;

    setTyping(true);
    const typingTimer = setTimeout(() => {
      setTyping(false);
      setVisibleCount((c) => c + 1);
    }, delay);

    return () => clearTimeout(typingTimer);
  }, [visibleCount]);

  const currentTypingRole =
    visibleCount < demoConversation.length
      ? demoConversation[visibleCount].role
      : null;

  return (
    <section className="py-20 relative overflow-hidden" aria-labelledby="demo-heading">
      <div className="absolute inset-0 pointer-events-none">
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[400px] rounded-full bg-primary/5 blur-[120px]" />
      </div>
      <div className="container mx-auto px-4 relative z-10">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-10"
        >
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-[11px] font-semibold tracking-widest uppercase bg-primary/10 text-primary border border-primary/20 mb-4">
            <Sparkles className="w-3.5 h-3.5" /> Live Demo
          </div>
          <h2 id="demo-heading" className="font-display text-3xl md:text-4xl font-bold text-foreground mb-3">
            See SimPilot.AI in Action
          </h2>
          <p className="text-muted-foreground max-w-xl mx-auto">
            Watch how SimPilot.AI uses the Socratic method to teach — not just answer.
          </p>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ delay: 0.15 }}
          className="max-w-2xl mx-auto"
        >
          {/* Chat window */}
          <div className="rounded-2xl border border-border bg-card shadow-lg overflow-hidden">
            {/* Header bar */}
            <div className="flex items-center gap-3 px-5 py-3 border-b border-border bg-secondary/40">
              <div className="w-8 h-8 rounded-full bg-primary/15 flex items-center justify-center">
                <Bot className="w-4 h-4 text-primary" />
              </div>
              <div>
                <p className="text-sm font-semibold text-foreground">SimPilot.AI CFI</p>
                <p className="text-[10px] text-muted-foreground">Ground School — Aerodynamics</p>
              </div>
              <div className="ml-auto flex items-center gap-1.5">
                <span className="w-2 h-2 rounded-full bg-primary animate-pulse" />
                <span className="text-[10px] text-muted-foreground">Online</span>
              </div>
            </div>

            {/* Messages area */}
            <div className="p-4 space-y-3 min-h-[320px] max-h-[420px] overflow-y-auto">
              <AnimatePresence mode="popLayout">
                {demoConversation.slice(0, visibleCount).map((msg, i) => (
                  <motion.div
                    key={i}
                    initial={{ opacity: 0, y: 12, scale: 0.95 }}
                    animate={{ opacity: 1, y: 0, scale: 1 }}
                    transition={{ duration: 0.35 }}
                    className={`flex gap-2.5 ${msg.role === "user" ? "flex-row-reverse" : ""}`}
                  >
                    <div
                      className={`w-7 h-7 rounded-full flex items-center justify-center shrink-0 mt-0.5 ${
                        msg.role === "assistant"
                          ? "bg-primary/15"
                          : "bg-accent/20"
                      }`}
                    >
                      {msg.role === "assistant" ? (
                        <Bot className="w-3.5 h-3.5 text-primary" />
                      ) : (
                        <User className="w-3.5 h-3.5 text-accent-foreground" />
                      )}
                    </div>
                    <div
                      className={`rounded-xl px-4 py-2.5 max-w-[80%] text-sm leading-relaxed ${
                        msg.role === "assistant"
                          ? "bg-secondary/60 text-foreground border border-border/40"
                          : "bg-primary text-primary-foreground"
                      }`}
                    >
                      {msg.text}
                    </div>
                  </motion.div>
                ))}
              </AnimatePresence>

              {/* Typing indicator */}
              {typing && currentTypingRole && (
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  className={`flex gap-2.5 ${currentTypingRole === "user" ? "flex-row-reverse" : ""}`}
                >
                  <div
                    className={`w-7 h-7 rounded-full flex items-center justify-center shrink-0 ${
                      currentTypingRole === "assistant" ? "bg-primary/15" : "bg-accent/20"
                    }`}
                  >
                    {currentTypingRole === "assistant" ? (
                      <Bot className="w-3.5 h-3.5 text-primary" />
                    ) : (
                      <User className="w-3.5 h-3.5 text-accent-foreground" />
                    )}
                  </div>
                  <div className="rounded-xl px-4 py-3 bg-secondary/60 border border-border/40 flex items-center gap-1">
                    <span className="w-1.5 h-1.5 rounded-full bg-muted-foreground/50 animate-bounce [animation-delay:0ms]" />
                    <span className="w-1.5 h-1.5 rounded-full bg-muted-foreground/50 animate-bounce [animation-delay:150ms]" />
                    <span className="w-1.5 h-1.5 rounded-full bg-muted-foreground/50 animate-bounce [animation-delay:300ms]" />
                  </div>
                </motion.div>
              )}
            </div>

            {/* Input bar (decorative) */}
            <div className="px-4 py-3 border-t border-border bg-secondary/20">
              <div className="flex items-center gap-2 rounded-lg border border-border bg-background px-3 py-2">
                <span className="text-sm text-muted-foreground/50 flex-1">Ask your CFI anything…</span>
                <div className="w-7 h-7 rounded-md bg-primary/20 flex items-center justify-center">
                  <Sparkles className="w-3.5 h-3.5 text-primary" />
                </div>
              </div>
            </div>
          </div>

          <p className="text-center text-[11px] text-muted-foreground mt-3">
            This is a simulated demo — your real conversations are even better.
          </p>
        </motion.div>
      </div>
    </section>
  );
};

export default AnimatedChatDemo;
