/**
 * SimPilot Bridge — Lightweight Auto-Updater
 * ---------------------------------------------------------------------------
 * Polls the GitHub Releases "latest.yml" feed (generated by the CI workflow)
 * once on launch and then every 6 hours. When a newer version is found:
 *   1. Downloads the installer .exe to the user's temp folder
 *   2. Verifies SHA-512 against latest.yml
 *   3. Notifies the renderer; user clicks "Install now" → we spawn the
 *      installer with /SILENT and quit, letting the new version take over.
 *
 * Why not electron-updater?
 *   electron-updater wants a code-signed app + electron-builder-style packaging.
 *   This module is a 100-line equivalent that works with plain @electron/packager
 *   + Inno Setup, which is exactly our pipeline.
 */

const { app, dialog, shell } = require("electron");
const https = require("node:https");
const http = require("node:http");
const fs = require("node:fs");
const path = require("node:path");
const os = require("node:os");
const crypto = require("node:crypto");
const { spawn } = require("node:child_process");

const FEED_URL =
  process.env.SIMPILOT_UPDATE_FEED ||
  "https://github.com/Sesarch/SimPilot-ai/releases/latest/download/latest.yml";
const POLL_INTERVAL_MS = 6 * 60 * 60 * 1000; // 6h

let mainWindow = null;
let pollTimer = null;
let downloading = false;

function log(msg) {
  console.log(`[updater] ${msg}`);
  mainWindow?.webContents.send("bridge:log", `[updater] ${msg}`);
}

// Tiny YAML parser — latest.yml only uses key: value + a single nested list.
function parseLatestYml(text) {
  const out = { files: [] };
  const lines = text.split(/\r?\n/);
  let currentFile = null;
  for (const raw of lines) {
    const line = raw.replace(/\s+$/, "");
    if (!line) continue;
    if (/^\s*-\s+url:\s*(.+)$/.test(line)) {
      currentFile = { url: RegExp.$1.trim() };
      out.files.push(currentFile);
      continue;
    }
    if (currentFile && /^\s+(\w+):\s*(.+)$/.test(line)) {
      currentFile[RegExp.$1] = RegExp.$2.trim();
      continue;
    }
    if (/^(\w+):\s*(.*)$/.test(line)) {
      out[RegExp.$1] = RegExp.$2.trim().replace(/^['"]|['"]$/g, "");
    }
  }
  return out;
}

function compareSemver(a, b) {
  const pa = a.split(".").map(Number);
  const pb = b.split(".").map(Number);
  for (let i = 0; i < 3; i++) {
    const d = (pa[i] || 0) - (pb[i] || 0);
    if (d !== 0) return d;
  }
  return 0;
}

function fetchText(url, redirects = 5) {
  return new Promise((resolve, reject) => {
    const lib = url.startsWith("https:") ? https : http;
    lib
      .get(url, { headers: { "User-Agent": "SimPilotBridge-Updater" } }, (res) => {
        if ([301, 302, 307, 308].includes(res.statusCode) && res.headers.location && redirects > 0) {
          res.resume();
          return resolve(fetchText(res.headers.location, redirects - 1));
        }
        if (res.statusCode !== 200) {
          res.resume();
          return reject(new Error(`HTTP ${res.statusCode} fetching ${url}`));
        }
        let body = "";
        res.setEncoding("utf8");
        res.on("data", (c) => (body += c));
        res.on("end", () => resolve(body));
      })
      .on("error", reject);
  });
}

function downloadFile(url, destPath, onProgress, redirects = 5) {
  return new Promise((resolve, reject) => {
    const lib = url.startsWith("https:") ? https : http;
    lib
      .get(url, { headers: { "User-Agent": "SimPilotBridge-Updater" } }, (res) => {
        if ([301, 302, 307, 308].includes(res.statusCode) && res.headers.location && redirects > 0) {
          res.resume();
          return resolve(downloadFile(res.headers.location, destPath, onProgress, redirects - 1));
        }
        if (res.statusCode !== 200) {
          res.resume();
          return reject(new Error(`HTTP ${res.statusCode} downloading ${url}`));
        }
        const total = Number(res.headers["content-length"]) || 0;
        let received = 0;
        const file = fs.createWriteStream(destPath);
        res.on("data", (chunk) => {
          received += chunk.length;
          if (total) onProgress?.(received / total);
        });
        res.pipe(file);
        file.on("finish", () => file.close(() => resolve(destPath)));
        file.on("error", reject);
      })
      .on("error", reject);
  });
}

function sha512Base64(filePath) {
  return new Promise((resolve, reject) => {
    const hash = crypto.createHash("sha512");
    const stream = fs.createReadStream(filePath);
    stream.on("data", (d) => hash.update(d));
    stream.on("end", () => resolve(hash.digest("base64")));
    stream.on("error", reject);
  });
}

async function checkForUpdate({ silent = false } = {}) {
  if (downloading) return;
  try {
    log(`checking ${FEED_URL}`);
    const text = await fetchText(FEED_URL);
    const feed = parseLatestYml(text);
    const remote = feed.version;
    const current = app.getVersion();
    if (!remote) throw new Error("latest.yml missing 'version'");
    log(`current=${current} remote=${remote}`);
    if (compareSemver(remote, current) <= 0) {
      if (!silent) mainWindow?.webContents.send("updater:status", { upToDate: true, current, remote });
      return;
    }
    const file = feed.files?.[0];
    if (!file?.url) throw new Error("latest.yml has no installer file");
    const downloadUrl = new URL(file.url, FEED_URL).toString();
    const expectedSha = file.sha512 || feed.sha512;

    mainWindow?.webContents.send("updater:status", { updateAvailable: true, current, remote });

    downloading = true;
    const tmp = path.join(os.tmpdir(), `SimPilotBridge-Setup-${remote}.exe`);
    log(`downloading ${downloadUrl} → ${tmp}`);
    await downloadFile(downloadUrl, tmp, (p) =>
      mainWindow?.webContents.send("updater:progress", { percent: Math.round(p * 100) })
    );

    if (expectedSha) {
      const actual = await sha512Base64(tmp);
      if (actual !== expectedSha) {
        try { fs.unlinkSync(tmp); } catch {/* noop */}
        throw new Error("SHA-512 mismatch — refusing to install corrupted update");
      }
      log("checksum verified ✓");
    }

    downloading = false;
    mainWindow?.webContents.send("updater:status", { downloaded: true, version: remote, installerPath: tmp });

    const choice = await dialog.showMessageBox(mainWindow, {
      type: "info",
      buttons: ["Install &restart now", "Later"],
      defaultId: 0,
      cancelId: 1,
      title: "SimPilot Bridge update ready",
      message: `Version ${remote} is ready to install.`,
      detail: `You're on ${current}. The installer will run silently and SimPilot Bridge will restart automatically.`,
    });

    if (choice.response === 0) installAndRestart(tmp);
  } catch (err) {
    downloading = false;
    log(`ERROR: ${err.message}`);
    if (!silent) mainWindow?.webContents.send("updater:status", { error: err.message });
  }
}

function installAndRestart(installerPath) {
  log(`launching installer: ${installerPath}`);
  // /SILENT shows progress but no prompts; /NORESTART so we control quitting.
  const child = spawn(installerPath, ["/SILENT", "/NORESTART"], {
    detached: true,
    stdio: "ignore",
  });
  child.unref();
  setTimeout(() => app.quit(), 800);
}

function start(window) {
  mainWindow = window;
  // First check 30s after launch so we don't block startup.
  setTimeout(() => checkForUpdate({ silent: true }), 30_000);
  pollTimer = setInterval(() => checkForUpdate({ silent: true }), POLL_INTERVAL_MS);
}

function stop() {
  if (pollTimer) clearInterval(pollTimer);
  pollTimer = null;
}

module.exports = { start, stop, checkForUpdate };
